### ISSUE TITLE
The Generation Update - TODO

### ISSUE THREAD

**Issue by Wugand** [mcenderdragon/Futurepack-API#116]
Dungeons - General:
- [ ] Reduce amount of loot
- [ ] No generation in Ozean biome
- [ ] Enemies in Dungeons (Robots)
- [ ] Fix dungeon Overlap
- [ ] Protect Dungeon (Destroy and Place)  {use World/Chunk Data}
- [ ] Spawn Teleporter "Monument" at surface, to access the dungeon (Teleporter)
- [ ] "Protection Room" or Boss-Fight to deactivate the Protection
- [ ] Dirty Magic to open doors

Dungeon - Rooms:
- [ ] Add more Rooms
- [ ] Fix generation of largest Rooms (don't spawn)
- [ ] Fix stair Rooms (don't spawn)
- [ ] No Central ladder
- [ ] Branched structure with blockades/locked doors
- [ ] Add Trap Rooms
- [ ] Add Puzzle Rooms

Menelaus - World:
- [ ] Bergpilze / Schrägpilze
- [ ] Obelisks at surface
- [ ] Undergound generation: CheeseSponge -- Nether-Like
- [ ] Large, Branched Caves
- [ ] Glowing mushrooms
- [ ] Lakes and Waterfalls
- [ ] Mushrooms, Mycelium, Vines

Others:
- [ ] Mushroom Science
- [ ] Menelaus Background story

**Comment by mcenderdragon** [comment]
Added Protection.

**Comment by mcenderdragon** [comment]
Added more Caves/bigger ones.

**Comment by mcenderdragon** [comment]
added mycelium like glowstone strctures around y:20

**Comment by mcenderdragon** [comment]
added 4 mushroms, and decorated underground with mycel. 
Also the new dungeons need more rooms.

**Comment by mcenderdragon** [comment]
since 1.12 the 4 new mushrooms spawn everywhere.

**Comment by Wugand** [comment]
TODO: check and add recipes for menelaus enviroment

**Comment by mcenderdragon** [comment]
dungeon overlap is fixed (new dimension), destruction also
