### ISSUE TITLE
TODO: Travel to Tyros

### ISSUE THREAD

**Issue by Wugand** [mcenderdragon/Futurepack-API#126]
- [x] *Make all Researches*
- [ ] Need a new way to get Coordinates
- [ ] Network Chip Recipe is wrong

@mcenderdragon 
- [x] Tyros dimension icon is shown as <?> if you not on Tyros
- [x] Advanced Board Computer need Information "FTL needed" (checkmark and waring message)
- [ ] FTL-Multiblock should get a power storage and consume NE

**Comment by Wugand** [comment]
@mcenderdragon:
Currently Importent for Tyros is:
Advanced Board Computer need Information "FTL needed" (checkmark and waring message)

**Comment by mcenderdragon** [comment]
I am thinkijng about not giving this hitn so see how many are readiung the researches.

**Comment by mcenderdragon** [comment]
Fixed <?> Tyros issue, added FTL needed info, with that power storage IDK..

**Comment by ghost** [comment]
>Need a new way to get Coordinates

Suggestions:
- Launch satellites - either launch one and then receiving antennae spits all accessible coordinates, or launch one and travel to a crash location to get the 'data'
- Send exploration drones (potentially can use parameters to search for specific planets, like exploration range)
- New ship module (like go to orbit-void, scan from there for nearby planets)
