### ISSUE TITLE
TODO: Finish Forstmaster

### ISSUE THREAD

**Issue by Wugand** [mcenderdragon/Futurepack-API#135]
- [x] remove most of the debug particles
- [x] support at least menelaus mushrooms (head is not removed)
- [x] gerneral mushroom-support would be nice
- [x] add crafting and research

**Comment by mcenderdragon** [comment]
Mushrooms are not trees after all a day are completely different generated, for example its all one block and doesn't have leaves. I dunno how to check if it's a tree or a mushrooms, maybe the huge ones (vanilla) have oredicts or something similar

**Comment by mcenderdragon** [comment]
removed debug particles

**Comment by mcenderdragon** [comment]
added mushroom support (menelaus + vanilla)

**Comment by mcenderdragon** [comment]
@Wugand crafting/research is your part.
