### ISSUE TITLE
[1.11] TODO: Finish Monocart

### ISSUE THREAD

**Issue by mcenderdragon** [mcenderdragon/Futurepack-API#139]
- [x] Spawn Item with Icon
- [ ] Check Entity working
- [ ] Check Rails working
- [ ] _make all Researches_

@Wugand
well what is needed for it?

**Comment by mcenderdragon** [comment]
TODO: Monorailstation: "Beim Einladen bedeutet die eingestellte Anzahl das das Monocart bis zu genau dieser Menge aufgefüllt wird, beim Ausladen wird genau diese Menge ausgeladen." - check that!

**Comment by mcenderdragon** [comment]
@Wugand everything is wokring right ? we also have al researches.

**Comment by mcenderdragon** [comment]
I hope we do...
